@startuml class Diagram
Company "1" - "*" User
Company "1" - "*" Organization
Organization "1" - "*" Section
Organization "1" - "*" User
Section "1" - "*" User
User "*" - "1" Role


class User{
    String recordId
    String name
    String surname
    String username
    String password
    Date createAt
    Date updateAt
    String createByUsername
    Company company
    Organization organization
    Section section
    Role role
}


class Company{
    String recordId
    String formattedName
    User[] users
    Organization[] organization
    Date createAt
    Date updateAt
}

class Organization{
    String recordId
    String name
    User[] users
    Company company
    Date createAt
    Date updateAt
}

class Section{
    String recordId
    String name
    User[] users
    Organization organization
    Company company
    Date createAt
    Date updateAt
}

class Role{
    String recordId
    String name
}

class File{
    String recordId
    String name
    String path
    Boolean isShared
    Boolean isPersonal
    Company company
    Organization organization
    Section section
    User createBy
    String createAt
    String updateAt
} 

@enduml
